### PR TITLE
Fix dependency issues in gemspec, use syck YAML engine, support Rails 3

### PR DESCRIPTION
**Pull request by andrewferk**
The gemspec was requiring lib/zencoder-fetcher.rb which was requiring gem libraries, such as httpparty, but if they are not installed, the installation of the gem will fail. You do have these gems as dependencies in the gemspec, but they were being loaded before gem was installing them.  This was fixed by smallacts in https://github.com/andrewferk/zencoder-fetcher/commit/f4e72cc2617849c4aa18403c317dd31f98fb8505.

The latest version of Ruby is now using the pysck yaml parser, which is more strict than the older syck yaml parser. Your json responses are not putting timestamps in double quotes, so the psyck yaml parser complains; the syck yaml parser does not complain on this.  This is fixed in my commits https://github.com/andrewferk/zencoder-fetcher/commit/a56838046169d6533a2f56251087a55d609f1945 and https://github.com/andrewferk/zencoder-fetcher/commit/34ca2db831b07ac3e833af98f142bf6312b3c6cb.

Also, Rails 3 should also be supported. This is fixed in commit https://github.com/andrewferk/zencoder-fetcher/commit/1b4d966aaa485a543f3df8e796d4abd7d1bbf7e1.

Thank you.

### CODE REVIEW

**Comment by bullfight** [comment]
when I try to install this I get

```
rubygems/requirement.rb:193:in `block in fix_syck_default_key_in_requirements': uninitialized constant Syck::Syck (NameError)

```

**Comment by andrewferk** [comment]
What version of Ruby and RubyGems are you using? I'll see if I can find a solution.

Thank you.

**Comment by bullfight** [comment]
no problem.

ruby-1.9.2-p290 [ x86_64 ]
rubygems-update (1.8.10)

**Comment by andrewferk** [comment]
I started with a new Ruby-1.9.2-p290 install, and confirm the issue you are having.

I can no longer reproduce the YAML issue I was having before, so the use of syck may not be needed anyways. It could have been possible that another gem I was using was breaking it, as moving from syck to psyck has been a headache for some.

There is still an issue with the dependencies being required before they may be installed.

I'll remove the syck commits, and resubmit a pull request for the other patches.

Thank you for your help.

**Pull request closed without merging**
